### ISSUE TITLE
usage of term 'MacaqueNet data'

### ISSUE THREAD

**Issue by gobbios** [MacaqueNet/database#2]
I just stumbled over the use of 'MacaqueNet data' in two paragraphs in the readme. I think we should avoid that term because it suggests that MacaqueNet owns the data, which is not the case.

In the first case we could just omit the term altogether: "We always welcome new projects ~~using MacaqueNet data~~ or new data contributions..."

Second case: "...use of data hosted at the MacaqueNet database. ~~MacaqueNet~~ data can be requested..."

**Comment by DelphineDeMoor** [comment]
updated
